trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  azureSubscription: "d923be12-0a8a-4ad6-aec7-cd91a06c8af2"
  appName: "final"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName: "Install dependencies"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "."
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/app.zip"
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: "$(azureSubscription)"
      appName: "$(appName)"
      package: "$(Build.ArtifactStagingDirectory)/app.zip"
